### ISSUE TITLE
Fix UI : Encoding a new partner is not working.

### ISSUE THREAD

**Issue by Dragomitch** [Dragomitch/PAE-PostRemise#16]
Exception : 

2017-11-04 11:42:16 (presentation.RouteResolver.findRoute) - INFO: Looking for the route matching: PUT /mobilityChoices/9/confirmWithNewPartner
2017-11-04 11:42:16 (presentation.RouteResolver.findRoute) - INFO: Route found: PUT /mobilitychoices/{id}/confirmWithNewPartner --> ucc.implementations.MobilityChoiceUccImpl.confirmWithNewPartner
2017-11-04 11:42:16 (presentation.Invoker.hasPermission) - INFO: Requester has right permissions
2017-11-04 11:42:16 (presentation.ExceptionHandler.handleException) - INFO: Handling IllegalArgumentException: 400 Bad Request
2017-11-04 11:42:16 (presentation.ExceptionHandler.handleException) - INFO: Message: Impossible to deserialize Json String
2017-11-04 11:42:16 (presentation.ExceptionHandler.handleException) - INFO: Cause: 
com.owlike.genson.JsonBindingException: Could not deserialize to property 'address' of class class business.implementations.PartnerImpl
	at com.owlike.genson.reflect.PropertyMutator.couldNotDeserialize(PropertyMutator.java:50)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:33)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:121)
	at com.owlike.genson.Genson.deserializeInto(Genson.java:424)
	at com.owlike.genson.Genson.deserializeInto(Genson.java:392)
	at presentation.JsonSerializer.deserialize(JsonSerializer.java:124)
	at presentation.Invoker.mapMethodArguments(Invoker.java:115)
	at presentation.Invoker.invoke(Invoker.java:58)
	at presentation.RoutingServlet.service(RoutingServlet.java:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to property 'id' of class class business.implementations.AddressImpl
	at com.owlike.genson.reflect.PropertyMutator.couldNotDeserialize(PropertyMutator.java:50)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:33)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:121)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:102)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.deserialize(NullConverterFactory.java:77)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:31)
	... 30 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.owlike.genson.stream.JsonReader.valueAsInt(JsonReader.java:215)
	at com.owlike.genson.convert.DefaultConverters$IntegerConverter.deserialize(DefaultConverters.java:429)
	at com.owlike.genson.convert.DefaultConverters$IntegerConverter.deserialize(DefaultConverters.java:416)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.deserialize(NullConverterFactory.java:77)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:31)
	... 34 more

java.lang.IllegalArgumentException: Impossible to deserialize Json String
	at presentation.JsonSerializer.deserialize(JsonSerializer.java:126)
	at presentation.Invoker.mapMethodArguments(Invoker.java:115)
	at presentation.Invoker.invoke(Invoker.java:58)
	at presentation.RoutingServlet.service(RoutingServlet.java:87)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to property 'address' of class class business.implementations.PartnerImpl
	at com.owlike.genson.reflect.PropertyMutator.couldNotDeserialize(PropertyMutator.java:50)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:33)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:121)
	at com.owlike.genson.Genson.deserializeInto(Genson.java:424)
	at com.owlike.genson.Genson.deserializeInto(Genson.java:392)
	at presentation.JsonSerializer.deserialize(JsonSerializer.java:124)
	... 26 more
Caused by: com.owlike.genson.JsonBindingException: Could not deserialize to property 'id' of class class business.implementations.AddressImpl
	at com.owlike.genson.reflect.PropertyMutator.couldNotDeserialize(PropertyMutator.java:50)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:33)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:121)
	at com.owlike.genson.reflect.BeanDescriptor.deserialize(BeanDescriptor.java:102)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.deserialize(NullConverterFactory.java:77)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:31)
	... 30 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.owlike.genson.stream.JsonReader.valueAsInt(JsonReader.java:215)
	at com.owlike.genson.convert.DefaultConverters$IntegerConverter.deserialize(DefaultConverters.java:429)
	at com.owlike.genson.convert.DefaultConverters$IntegerConverter.deserialize(DefaultConverters.java:416)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.deserialize(NullConverterFactory.java:77)
	at com.owlike.genson.reflect.PropertyMutator.deserialize(PropertyMutator.java:31)
	... 34 more
2017-11-04 11:42:16 (presentation.RouteResolver.findRoute) - INFO: Looking for the route matching: GET /mobilityChoices
2017-11-04 11:42:16 (presentation.RouteResolver.findRoute) - INFO: Route found: GET /mobilityChoices --> ucc.implementations.MobilityChoiceUccImpl.showAll
2017-11-04 11:42:16 (presentation.Invoker.hasPermission) - INFO: Requester has right permissions
2017-11-04 11:42:16 (ucc.implementations.UnitOfWorkImpl.startTransaction) - INFO: Opening connection
2017-11-04 11:42:16 (ucc.implementations.UnitOfWorkImpl.commit) - INFO: Committing changes
2017-11-04 11:42:16 (ucc.implementations.UnitOfWorkImpl.commit) - INFO: Closing connection

**Comment by Dragomitch** [comment]
Main Issue solved but: 

- still got a NPE while trying to retrieving new partner without partner-option
- business problem : we can have an Erabel in Afghanistan

**Comment by Dragomitch** [comment]
- Major problem solved in 36d291d011eb12730f6a0836919cc51cfc6779a5
- Still have to fix the countries for the different programs
